#include <bits/stdc++.h>
using namespace std;
int n,x,y,d,g;
int arr[104][104];
int dy[4] = {0,-1,0,1};
int dx[4] = {1,0,-1,0};

// Key take-away for this problem:
// Record the directions that each point has to take per generation
// 0th: 0
// 1st: 0,1
// 2nd: 0,1,2,1 => (1+1, 0+1)
// 3rd: 0,1,2,1,2,3,2,1 => (1+1, 2+1, 1+1, 0+1)
// -> Further directions are generated by iterating through the previous directions
// in reverse order and adding 1 to it.

void print(){
    cout << "------------------\n";
    for (int i=0; i<10; i++){
        for (int j=0; j<10; j++){
            cout << arr[i][j] << " ";
        }
        cout << "\n";
    }
}

int countSquares(){
    int cnt = 0;
    for (int i=0; i<101; i++){
        for (int j=0; j<101; j++){
            if (arr[i][j] && arr[i+1][j] && arr[i][j+1] && arr[i+1][j+1]){
                cnt++;
            }
        }
    }   

    return cnt;
}

void markSpots(int y, int x, vector<int>instr){

    arr[y][x] = 1;

    for (int i=0; i<instr.size(); i++){
        int dir = instr[i];

        int ny = y + dy[dir];
        int nx = x + dx[dir];

        arr[ny][nx] = 1;

        y = ny;
        x = nx;
    }
}

int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(NULL); cout.tie(NULL);

    cin >> n;
    vector<vector<int>>tmp;
    for (int i=0; i<n; i++){
        vector<int>v;
        cin >> x >> y >> d >> g;
        v.push_back(d);
        for (int j=0; j<g; j++){
            for (int k=v.size() - 1; k>=0; k--){
                v.push_back((v[k] + 1) % 4);
            }
        }

        markSpots(y,x,v);
    }

    int ret = countSquares();
    cout << ret << "\n";

    return 0;
}